package qut.edu.au.pqcsebase.algorithms;

import qut.edu.au.pqcsebase.tools.BigIntMatrix;

import static qut.edu.au.pqcsebase.algorithms.RandBasis.LLL;
import static qut.edu.au.pqcsebase.algorithms.RandBasis.randBasisPre;
import static qut.edu.au.pqcsebase.tools.BigIntMatrix.inverse;

public class BasisDel {

    /**
     * Basis Deletion Algorithm
     *
     * @param A    The original basis matrix
     * @param R    Zq-invertible R matrix  generated by SampleR sigmaR = sqrt(n * log q)*w(sqrt(log m))
     * @param T_A  The target vectors associated with basis A
     * @param sigma    The parameter for the Gaussian sampling
     * @return     The new basis matrix B after deletion
     */
    public static BigIntMatrix basisDel(BigIntMatrix A, BigIntMatrix R, BigIntMatrix T_A, double sigma, long nParam) {

        //BigIntMatrix B = A.multiplyQ(inverse(R));
        //T'_B := {R*a_1, ..., R*a_m}c
        BigIntMatrix T_prime = R.multiply(T_A);

        BigIntMatrix T_double_prime = LLL(T_prime, 0.99);
        System.out.println("Finish LLL in BasisDel.");

        BigIntMatrix Tb = randBasisPre(T_double_prime, sigma, nParam);
        System.out.println("Finish RandBasis in BasisDel.");

        return Tb;
    }
}
